# Replace the value below with your unique Fly.io app name before deploying!
app = "REPLACE_WITH_YOUR_UNIQUE_FLYIO_APP_NAME"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"
  PUPPETEER_HEADLESS = "new"
  LMARENA_URL = "https://beta.lmarena.ai/"
  DEBUG_MODE = "false" 

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024